project:
  type: website
  output-dir: docs
  preview:
    port: 8080

website:
  title: "Engineering practices in ML"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Course problems"
        contents:
          - 1.entry.qmd
          - 2.replication_crisis.qmd
      - section: "Team work"
        contents:
          - 3.team_work.qmd
          - 4.git_workflow.qmd
      - section: "Software development"
        contents:
          - 5.dependencies.qmd
          - 6.code_styles.qmd
          - 7.testing.qmd
      - section: "Documentation"
        contents:
          - 8.generate_docs.qmd
      - section: "Data versioning"
        contents:
          - 9.dvc.qmd
      - section: "Pipelines"
        contents:
          - 10.snakemake.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



